import os

class Config():
    GITHUB_APP_ID = os.getenv("GITHUB_APP_ID")
    GITHUB_OWNER = os.getenv("GITHUB_OWNER")
    GITHUB_KARMA_REPO = os.getenv("GITHUB_KARMA_REPO")
    GITHUB_CERT_FILE_PATH = os.getenv("GITHUB_CERT_FILE_PATH")
    GITHUB_DATA_DIR = os.getenv("GITHUB_DATA_DIR")
    CONTRIBUTORS_FILENAME = os.getenv("CONTRIBUTORS_FILENAME")
    PAYMENTS_FILENAME = os.getenv("PAYMENTS_FILENAME")
    FORMAT_TIMESTAMP = "%Y-%m-%dT%H:%M:%S"
    FORMAT_TIMESTAMP_TZ = '%Y-%m-%dT%H:%M:%S.%f%z'
    SYNC_INTERVAL = 15
    